version: '3.8'
services:
  mongodb:
    image: mongo
    volumes:
      - goalsdata:/data/db
    env_file:
      - ./env/mongo_env
  backend:
    build: ./backend
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend_env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
volumes:
  goalsdata:
  logs: